version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: nafeo
      POSTGRES_USER: 1234
      POSTGRES_DB: todo-postgres
    ports:
      - "5432:5432"
